cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/bundle"

brew "bat"
brew "diff-so-fancy"
brew "fzf"
brew "git"
brew "nvm"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "tmux"
brew "vim"
brew "zsh"
brew "zsh-completions"
brew "autojump"

cask "fluor"
cask "iterm2"